name: Go CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ Set up Go
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.25

      # 3️⃣ Install dependencies
      - name: Download Go modules
        run: go mod download

      # 4️⃣ Install golangci-lint
      - name: Install golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s latest
          export PATH=$PATH:$$HOME/.golangci-lint/bin
      # 6️⃣ Lint
      - name: Lint code
        run: make lint

      # 7️⃣ Build Go binary
      - name: Build Go binary
        run: make build

      # 8️⃣ Build Docker image
      - name: Build Docker image
        run: make docker-build